remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Nombres y Apellidos
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgiaNsXbSv7-iN3NavMwbUvX6fkNOZ4nC5kA&usqp=CAU

